In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
movies = pd.merge(movies, credits, on='title', how='outer')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,1500000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 9648, ""na...",http://www.hashtaghorror.com/,301325,[],de,#Horror,"Inspired by actual events, a group of 12 year ...",2.815228,"[{""name"": ""AST Studios"", ""id"": 75277}, {""name""...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Death is trending.,#Horror,3.3,52,301325,"[{""cast_id"": 0, ""character"": ""Alex's 12-Step F...","[{""credit_id"": ""545bbac70e0a261fb6002329"", ""de..."

In [7]:
#genres
#id
#keywords
#title
#overview
#cast
#crew

movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,301325,#Horror,"Inspired by actual events, a group of 12 year ...","[{""id"": 18, ""name"": ""Drama""}, {""id"": 9648, ""na...",[],"[{""cast_id"": 0, ""character"": ""Alex's 12-Step F...","[{""credit_id"": ""545bbac70e0a261fb6002329"", ""de..."
1,19913,(500) Days of Summer,"Tom (Joseph Gordon-Levitt), greeting-card writ...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 572, ""nam...","[{""cast_id"": 4, ""character"": ""Tom Hansen"", ""cr...","[{""credit_id"": ""52fe47f99251416c750abaa5"", ""de..."
2,333371,10 Cloverfield Lane,"After a car accident, Michelle awakens to find...","[{""id"": 53, ""name"": ""Thriller""}, {""id"": 878, ""...","[{""id"": 1930, ""name"": ""kidnapping""}, {""id"": 23...","[{""cast_id"": 2, ""character"": ""Michelle"", ""cred...","[{""credit_id"": ""57627624c3a3680682000872"", ""de..."
3,345003,10 Days in a Madhouse,"Nellie Bly, a 23 year-old reporter for Joseph ...","[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 1568, ""name"": ""undercover""}, {""id"": 49...","[{""cast_id"": 2, ""character"": ""Nellie Bly"", ""cr...","[{""credit_id"": ""594efa1fc3a36832650455ff"", ""de..."
4,4951,10 Things I Hate About You,"Bianca, a tenth grader, has never gone on a da...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 497, ""name"": ""shakespeare""}, {""id"": 59...","[{""cast_id"": 2, ""character"": ""Patrick Verona"",...","[{""credit_id"": ""52fe43e6c3a36847f807731d"", ""de..."

In [10]:
 #check  missing data
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace= True)

In [12]:
 #check duplicate data
movies.duplicated().sum()

0

In [25]:
movies.iloc[0].genres

'[{"id": 18, "name": "Drama"}, {"id": 9648, "name": "Mystery"}, {"id": 27, "name": "Horror"}, {"id": 53, "name": "Thriller"}]'

In [27]:
#'[{"id": 18, "name": "Drama"}, {"id": 9648, "name": "Mystery"}, {"id": 27, "name": "Horror"}, {"id": 53, "name": "Thriller"}]'
#['Action', 'Adventure', 'Fantasy', 'SciFi']

In [42]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [44]:
convert('[{"id": 18, "name": "Drama"}, {"id": 9648, "name": "Mystery"}, {"id": 27, "name": "Horror"}, {"id": 53, "name": "Thriller"}]')

['Drama', 'Mystery', 'Horror', 'Thriller']

In [46]:
#for this error :  string indices must be integers, not 'str'
import ast
ast.literal_eval('[{"id": 18, "name": "Drama"}, {"id": 9648, "name": "Mystery"}, {"id": 27, "name": "Horror"}, {"id": 53, "name": "Thriller"}]')

[{'id': 18, 'name': 'Drama'},
 {'id': 9648, 'name': 'Mystery'},
 {'id': 27, 'name': 'Horror'},
 {'id': 53, 'name': 'Thriller'}]

In [48]:
movies['genres'] = movies['genres'].apply(convert)

In [50]:
movies['keywords'] = movies['keywords'].apply(convert)

In [51]:
def convert3(obj):
    cnt = 0
    L = []
    for i in ast.literal_eval(obj):
        if cnt != 3:
            L.append(i['name'])
            cnt+= 1
        else:
            break
    return L

In [54]:
movies['cast'] = movies['cast'].apply(convert3)

In [55]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,301325,#Horror,"Inspired by actual events, a group of 12 year ...","[Drama, Mystery, Horror, Thriller]",[],"[Taryn Manning, Natasha Lyonne, ChloÃ« Sevigny]","[{""credit_id"": ""545bbac70e0a261fb6002329"", ""de..."
1,19913,(500) Days of Summer,"Tom (Joseph Gordon-Levitt), greeting-card writ...","[Comedy, Drama, Romance]","[date, sex, jealousy, fight, architect, galler...","[Joseph Gordon-Levitt, Zooey Deschanel, ChloÃ« ...","[{""credit_id"": ""52fe47f99251416c750abaa5"", ""de..."
2,333371,10 Cloverfield Lane,"After a car accident, Michelle awakens to find...","[Thriller, Science Fiction, Drama]","[kidnapping, bunker, paranoia, basement, survi...","[Mary Elizabeth Winstead, John Goodman, John G...","[{""credit_id"": ""57627624c3a3680682000872"", ""de..."
3,345003,10 Days in a Madhouse,"Nellie Bly, a 23 year-old reporter for Joseph ...",[Drama],"[undercover, insane asylum, reporter]","[Caroline Barry, Christopher Lambert, Kelly Le...","[{""credit_id"": ""594efa1fc3a36832650455ff"", ""de..."
4,4951,10 Things I Hate About You,"Bianca, a tenth grader, has never gone on a da...","[Comedy, Romance, Drama]","[shakespeare, sister, high school, cannabis, d...","[Heath Ledger, Julia Stiles, Joseph Gordon-Lev...","[{""credit_id"": ""52fe43e6c3a36847f807731d"", ""de..."

In [56]:
movies['crew'][0]

'[{"credit_id": "545bbac70e0a261fb6002329", "department": "Writing", "gender": 1, "id": 61111, "job": "Screenplay", "name": "Tara Subkoff"}, {"credit_id": "545bbabf0e0a261fb9002212", "department": "Directing", "gender": 1, "id": 61111, "job": "Director", "name": "Tara Subkoff"}, {"credit_id": "545bbae4c3a36853500018a8", "department": "Production", "gender": 1, "id": 61111, "job": "Producer", "name": "Tara Subkoff"}, {"credit_id": "545bbad3c3a3685358001b92", "department": "Production", "gender": 0, "id": 1382445, "job": "Producer", "name": "Jason Ludman"}, {"credit_id": "545bbadbc3a368535d001e74", "department": "Production", "gender": 0, "id": 1382446, "job": "Producer", "name": "Oren Segal"}, {"credit_id": "545bbaf3c3a3685358001b9d", "department": "Production", "gender": 0, "id": 1382448, "job": "Producer", "name": "Brendan Walsh"}]'

In [57]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [62]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [64]:
movies.head(10)

,movie_id,title,overview,genres,keywords,cast,crew
0,301325,#Horror,"Inspired by actual events, a group of 12 year ...","[Drama, Mystery, Horror, Thriller]",[],"[Taryn Manning, Natasha Lyonne, ChloÃ« Sevigny]",[Tara Subkoff]
1,19913,(500) Days of Summer,"Tom (Joseph Gordon-Levitt), greeting-card writ...","[Comedy, Drama, Romance]","[date, sex, jealousy, fight, architect, galler...","[Joseph Gordon-Levitt, Zooey Deschanel, ChloÃ« ...",[Marc Webb]
2,333371,10 Cloverfield Lane,"After a car accident, Michelle awakens to find...","[Thriller, Science Fiction, Drama]","[kidnapping, bunker, paranoia, basement, survi...","[Mary Elizabeth Winstead, John Goodman, John G...",[Dan Trachtenberg]
3,345003,10 Days in a Madhouse,"Nellie Bly, a 23 year-old reporter for Joseph ...",[Drama],"[undercover, insane asylum, reporter]","[Caroline Barry, Christopher Lambert, Kelly Le...",[Timothy Hines]
4,4951,10 Things I Hate About You,"Bianca, a tenth grader, has never gone on a da...","[Comedy, Romance, Drama]","[shakespeare, sister, high school, cannabis, d...","[Heath Ledger, Julia Stiles, Joseph Gordon-Lev...",[Gil Junger]
5,10481,102 Dalmatians,Get ready for a howling good time as an all ne...,"[Comedy, Family]","[london england, prison, release from prison, ...","[Glenn Close, Ioan Gruffudd, Alice Evans]",[Kevin Lima]
6,13197,10th & Wolf,A former street tough returns to his Philadelp...,"[Action, Crime, Drama, Mystery, Thriller]","[undercover, mafia, mobster, crime family]","[James Marsden, Brian Dennehy, Leo Rossi]",[Robert Moresco]
7,9282,11:14,Tells the seemingly random yet vitally connect...,"[Crime, Drama, Thriller]","[alcohol, sex, robbery, secret, gun, ambulance...","[Henry Thomas, Blake Heron, Barbara Hershey]",[Greg Marcks]
8,389,12 Angry Men,The defense and the prosecution have rested an...,[Drama],"[judge, jurors, sultriness, death penalty, fat...","[Henry Fonda, Martin Balsam, John Fiedler]",[Sidney Lumet]
9,17134,12 Rounds,When New Orleans cop Danny Fisher prevents a b...,"[Action, Adventure, Drama, Thriller]","[police, cops, cat and mouse, family, revenge ...","[John Cena, Aidan Gillen, Ashley Scott]",[Renny Harlin]

In [66]:
movies['overview'][0]

'Inspired by actual events, a group of 12 year old girls face a night of horror when the compulsive addiction of an online social media game turns a moment of cyber bullying into a night of insanity.'

In [68]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [70]:
movies.head(10)

,movie_id,title,overview,genres,keywords,cast,crew
0,301325,#Horror,"[Inspired, by, actual, events,, a, group, of, ...","[Drama, Mystery, Horror, Thriller]",[],"[Taryn Manning, Natasha Lyonne, ChloÃ« Sevigny]",[Tara Subkoff]
1,19913,(500) Days of Summer,"[Tom, (Joseph, Gordon-Levitt),, greeting-card,...","[Comedy, Drama, Romance]","[date, sex, jealousy, fight, architect, galler...","[Joseph Gordon-Levitt, Zooey Deschanel, ChloÃ« ...",[Marc Webb]
2,333371,10 Cloverfield Lane,"[After, a, car, accident,, Michelle, awakens, ...","[Thriller, Science Fiction, Drama]","[kidnapping, bunker, paranoia, basement, survi...","[Mary Elizabeth Winstead, John Goodman, John G...",[Dan Trachtenberg]
3,345003,10 Days in a Madhouse,"[Nellie, Bly,, a, 23, year-old, reporter, for,...",[Drama],"[undercover, insane asylum, reporter]","[Caroline Barry, Christopher Lambert, Kelly Le...",[Timothy Hines]
4,4951,10 Things I Hate About You,"[Bianca,, a, tenth, grader,, has, never, gone,...","[Comedy, Romance, Drama]","[shakespeare, sister, high school, cannabis, d...","[Heath Ledger, Julia Stiles, Joseph Gordon-Lev...",[Gil Junger]
5,10481,102 Dalmatians,"[Get, ready, for, a, howling, good, time, as, ...","[Comedy, Family]","[london england, prison, release from prison, ...","[Glenn Close, Ioan Gruffudd, Alice Evans]",[Kevin Lima]
6,13197,10th & Wolf,"[A, former, street, tough, returns, to, his, P...","[Action, Crime, Drama, Mystery, Thriller]","[undercover, mafia, mobster, crime family]","[James Marsden, Brian Dennehy, Leo Rossi]",[Robert Moresco]
7,9282,11:14,"[Tells, the, seemingly, random, yet, vitally, ...","[Crime, Drama, Thriller]","[alcohol, sex, robbery, secret, gun, ambulance...","[Henry Thomas, Blake Heron, Barbara Hershey]",[Greg Marcks]
8,389,12 Angry Men,"[The, defense, and, the, prosecution, have, re...",[Drama],"[judge, jurors, sultriness, death penalty, fat...","[Henry Fonda, Martin Balsam, John Fiedler]",[Sidney Lumet]
9,17134,12 Rounds,"[When, New, Orleans, cop, Danny, Fisher, preve...","[Action, Adventure, Drama, Thriller]","[police, cops, cat and mouse, family, revenge ...","[John Cena, Aidan Gillen, Ashley Scott]",[Renny Harlin]

In [72]:
#Taryn Manning
#TarynManning
#apply transform

In [74]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [76]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [78]:
movies.head(10)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,301325,#Horror,"[Inspired, by, actual, events,, a, group, of, ...","[Drama, Mystery, Horror, Thriller]",[],"[TarynManning, NatashaLyonne, ChloÃ«Sevigny]",[TaraSubkoff],"[Inspired, by, actual, events,, a, group, of, ..."
1,19913,(500) Days of Summer,"[Tom, (Joseph, Gordon-Levitt),, greeting-card,...","[Comedy, Drama, Romance]","[date, sex, jealousy, fight, architect, galler...","[JosephGordon-Levitt, ZooeyDeschanel, ChloÃ«Gra...",[MarcWebb],"[Tom, (Joseph, Gordon-Levitt),, greeting-card,..."
2,333371,10 Cloverfield Lane,"[After, a, car, accident,, Michelle, awakens, ...","[Thriller, ScienceFiction, Drama]","[kidnapping, bunker, paranoia, basement, survi...","[MaryElizabethWinstead, JohnGoodman, JohnGalla...",[DanTrachtenberg],"[After, a, car, accident,, Michelle, awakens, ..."
3,345003,10 Days in a Madhouse,"[Nellie, Bly,, a, 23, year-old, reporter, for,...",[Drama],"[undercover, insaneasylum, reporter]","[CarolineBarry, ChristopherLambert, KellyLeBrock]",[TimothyHines],"[Nellie, Bly,, a, 23, year-old, reporter, for,..."
4,4951,10 Things I Hate About You,"[Bianca,, a, tenth, grader,, has, never, gone,...","[Comedy, Romance, Drama]","[shakespeare, sister, highschool, cannabis, de...","[HeathLedger, JuliaStiles, JosephGordon-Levitt]",[GilJunger],"[Bianca,, a, tenth, grader,, has, never, gone,..."
5,10481,102 Dalmatians,"[Get, ready, for, a, howling, good, time, as, ...","[Comedy, Family]","[londonengland, prison, releasefromprison, wom...","[GlennClose, IoanGruffudd, AliceEvans]",[KevinLima],"[Get, ready, for, a, howling, good, time, as, ..."
6,13197,10th & Wolf,"[A, former, street, tough, returns, to, his, P...","[Action, Crime, Drama, Mystery, Thriller]","[undercover, mafia, mobster, crimefamily]","[JamesMarsden, BrianDennehy, LeoRossi]",[RobertMoresco],"[A, former, street, tough, returns, to, his, P..."
7,9282,11:14,"[Tells, the, seemingly, random, yet, vitally, ...","[Crime, Drama, Thriller]","[alcohol, sex, robbery, secret, gun, ambulance...","[HenryThomas, BlakeHeron, BarbaraHershey]",[GregMarcks],"[Tells, the, seemingly, random, yet, vitally, ..."
8,389,12 Angry Men,"[The, defense, and, the, prosecution, have, re...",[Drama],"[judge, jurors, sultriness, deathpenalty, fath...","[HenryFonda, MartinBalsam, JohnFiedler]",[SidneyLumet],"[The, defense, and, the, prosecution, have, re..."
9,17134,12 Rounds,"[When, New, Orleans, cop, Danny, Fisher, preve...","[Action, Adventure, Drama, Thriller]","[police, cops, catandmouse, family, revengedrama]","[JohnCena, AidanGillen, AshleyScott]",[RennyHarlin],"[When, New, Orleans, cop, Danny, Fisher, preve..."

In [80]:
new_df = movies[['movie_id' , 'title', 'tags']]

In [82]:
new_df

,movie_id,title,tags
0,301325,#Horror,"[Inspired, by, actual, events,, a, group, of, ..."
1,19913,(500) Days of Summer,"[Tom, (Joseph, Gordon-Levitt),, greeting-card,..."
2,333371,10 Cloverfield Lane,"[After, a, car, accident,, Michelle, awakens, ..."
3,345003,10 Days in a Madhouse,"[Nellie, Bly,, a, 23, year-old, reporter, for,..."
4,4951,10 Things I Hate About You,"[Bianca,, a, tenth, grader,, has, never, gone,..."
...,...,...,...
4804,10664,[REC]Â²,"[The, action, continues, from, [REC],, with, t..."
4805,1946,eXistenZ,"[A, game, designer, on, the, run, from, assass..."
4806,7451,xXx,"[Xander, Cage, is, your, standard, adrenaline,..."
4807,11679,xXx: State of the Union,"[Ice, Cube, stars, as, Darius, Stone,, a, thri..."
4808,8202,Ã†on Flux,"[400, years, into, the, future,, disease, has,..."

In [84]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\JAYENDRA SINGH\AppData\Local\Temp\ipykernel_21332\394146094.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [86]:
new_df

,movie_id,title,tags
0,301325,#Horror,"Inspired by actual events, a group of 12 year ..."
1,19913,(500) Days of Summer,"Tom (Joseph Gordon-Levitt), greeting-card writ..."
2,333371,10 Cloverfield Lane,"After a car accident, Michelle awakens to find..."
3,345003,10 Days in a Madhouse,"Nellie Bly, a 23 year-old reporter for Joseph ..."
4,4951,10 Things I Hate About You,"Bianca, a tenth grader, has never gone on a da..."
...,...,...,...
4804,10664,[REC]Â²,"The action continues from [REC], with the medi..."
4805,1946,eXistenZ,A game designer on the run from assassins must...
4806,7451,xXx,Xander Cage is your standard adrenaline junkie...
4807,11679,xXx: State of the Union,"Ice Cube stars as Darius Stone, a thrill-seeki..."
4808,8202,Ã†on Flux,"400 years into the future, disease has wiped o..."

In [88]:
import nltk

In [89]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [92]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [94]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\JAYENDRA SINGH\AppData\Local\Temp\ipykernel_21332\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [96]:
!pip install nltk

Requirement already satisfied: nltk in f:\program files\anaconda\lib\site-packages (3.9.1)
Requirement already satisfied: click in f:\program files\anaconda\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in f:\program files\anaconda\lib\site-packages (from nltk) (1.1.1)
Requirement already satisfied: regex>=2021.8.3 in f:\program files\anaconda\lib\site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in f:\program files\anaconda\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: colorama in c:\users\jayendra singh\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)

In [98]:
new_df['tags'][0]

'inspir by actual events, a group of 12 year old girl face a night of horror when the compuls addict of an onlin social media game turn a moment of cyber bulli into a night of insanity. drama mysteri horror thriller tarynman natashalyonn chloÃ«sevigni tarasubkoff'

In [100]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\JAYENDRA SINGH\AppData\Local\Temp\ipykernel_21332\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [102]:
new_df.head()

,movie_id,title,tags
0,301325,#Horror,"inspir by actual events, a group of 12 year ol..."
1,19913,(500) Days of Summer,"tom (joseph gordon-levitt), greeting-card writ..."
2,333371,10 Cloverfield Lane,"after a car accident, michel awaken to find he..."
3,345003,10 Days in a Madhouse,"nelli bly, a 23 year-old report for joseph pul..."
4,4951,10 Things I Hate About You,"bianca, a tenth grader, ha never gone on a dat..."

In [104]:
#vectorization

In [106]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features= 5000, stop_words='english')

In [108]:
vectors = cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [109]:
vectors.shape

(4806, 5000)

In [110]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [111]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [116]:
# ['loved', 'loving', 'loves']
# ['love', 'love', 'love']

In [118]:
stem('Inspired by actual events, a group of 12 year old girls face a night of horror when the compulsive addiction of an online social media game turns a moment of cyber bullying into a night of insanity. Drama Mystery Horror Thriller TarynManning NatashaLyonne ChloÃ«Sevigny TaraSubkoff')

'inspir by actual events, a group of 12 year old girl face a night of horror when the compuls addict of an onlin social media game turn a moment of cyber bulli into a night of insanity. drama mysteri horror thriller tarynman natashalyonn chloÃ«sevigni tarasubkoff'

In [120]:
from sklearn.metrics.pairwise import cosine_similarity

In [122]:
similarity = cosine_similarity(vectors)

In [123]:
similarity[0]

array([1.        , 0.04675246, 0.08728716, ..., 0.03178209, 0.07905694,
       0.03001501])

In [124]:
def recommend(movie):
    if movie not in new_df['title'].values:
        print(f"Movie '{movie}' not found in the dataset.")
        return
        
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    print("Top 5 similar movies:\n")
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [125]:
recommend('10 Days in a Madhouse')

Top 5 similar movies:

Big Mommas: Like Father, Like Son
The Dog Lover
Hard Candy
Donnie Brasco
Bad Grandpa

In [130]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(989, 0.30429030972509225),
 (67, 0.2931977358041868),
 (1701, 0.272474630456533),
 (695, 0.27174648819470304),
 (1044, 0.2608745973749755)]

In [132]:
new_df

,movie_id,title,tags
0,301325,#Horror,"inspir by actual events, a group of 12 year ol..."
1,19913,(500) Days of Summer,"tom (joseph gordon-levitt), greeting-card writ..."
2,333371,10 Cloverfield Lane,"after a car accident, michel awaken to find he..."
3,345003,10 Days in a Madhouse,"nelli bly, a 23 year-old report for joseph pul..."
4,4951,10 Things I Hate About You,"bianca, a tenth grader, ha never gone on a dat..."
...,...,...,...
4804,10664,[REC]Â²,"the action continu from [rec], with the medic ..."
4805,1946,eXistenZ,a game design on the run from assassin must pl...
4806,7451,xXx,xander cage is your standard adrenalin junki w...
4807,11679,xXx: State of the Union,"ice cube star as dariu stone, a thrill-seek tr..."
4808,8202,Ã†on Flux,"400 year into the future, diseas ha wipe out t..."

In [134]:
import pickle

In [136]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [138]:
pickle.dump(new_df.to_dict(), open('movies_dict.pkl', 'wb'))

In [140]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [172]:
import bz2
import pickle

In [174]:
def decompress_pickle(file):
    with open(file, 'rb') as f:
        data = pickle.load(f)
    return data

In [176]:
model = decompress_pickle('similarity.pkl')